name: Full Pipeline Run

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        channels: conda-forge,bioconda,defaults
        channel-priority: strict
        mamba-version: "*"
        use-mamba: true
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge -c bioconda snakemake
        sudo apt-get update && sudo apt-get install -y graphviz
    
    - name: Run full pipeline
      shell: bash -l {0}
      run: |
        snakemake -j 2 --use-conda --conda-frontend mamba
    
    - name: List results
      run: |
        ls -la results/
        find results -name "*.png" -o -name "*.fasta" -o -name "*.txt" | sort
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: |
          results/
          ANALYSIS_SUMMARY.md
        retention-days: 30
    
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          results/pymol/Fn_overlay.png
          results/alignment/cas_dual_mafft.png
          results/workflow_dag.png
          ANALYSIS_SUMMARY.md
        body: |
          ## FnCas9 vs FnCas12a Analysis Results
          
          This release contains:
          - Structural overlay visualization
          - Sequence alignment conservation plot
          - Pipeline workflow diagram
          - Complete analysis summary
          
          See ANALYSIS_SUMMARY.md for detailed results.